In [324]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

In [325]:
data = pd.read_csv("dataa.csv", index_col=False)
# Drop the column named "Unnamed: 0"
data = data.drop(columns=["Unnamed: 0","ID"])
data['date'] = data['date'].str.split().str[0]
data

,date,campaign_type,region,customer_age_range,gender,sales,units_sold,clients_engaged,click_rate,conversion_rate
0,2019-02-19,Online Advertising,East,56+,Male,100735.32,64.0,2364.0,0.13,0.13
1,2019-04-08,Online Advertising,North,56+,Female,15722.29,77.0,684.0,0.24,0.13
2,2018-06-28,TV,North,26-35,Male,35385.73,1.0,2299.0,0.51,0.08
3,2019-06-10,Online Advertising,West,36-45,Male,116045.50,44.0,2332.0,0.97,0.09
4,2018-07-14,Email,East,36-45,Male,65039.93,20.0,2564.0,0.36,0.26
...,...,...,...,...,...,...,...,...,...,...
19974,2019-02-05,Online Advertising,East,26-35,Female,45562.64,8.0,642.0,1.36,0.16
19975,2018-11-20,Email,East,36-45,Male,31524.54,65.0,1982.0,0.28,0.03
19976,2021-01-05,Online Advertising,West,46-55,Female,67450.37,87.0,669.0,0.29,0.19
19977,2020-09-20,Online Advertising,West,18-25,Male,103822.94,66.0,2670.0,1.22,0.19
19978,2018-12-17,Direct Advertising,North,26-35,Male,70765.63,72.0,2825.0,0.25,0.18

In [326]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le_count = 0

for col in data:
    if data[col].dtype == 'object':
        if len(list(data[col].unique())) <= 3:
            le.fit(data[col])
            data[col] = le.transform(data[col])
            le_count += 1


data['date'] = pd.to_datetime(data['date'])

data['year'] = data['date'].dt.year
data['month'] = data['date'].dt.month
data['day'] = data['date'].dt.day

data = data.drop(columns=['date'])
import category_encoders as ce

data = pd.get_dummies(data, columns=['campaign_type'])
data = pd.get_dummies(data, columns=['region'])
data = data.replace({True: 1, False: 0})
mapping = {'18-25': 1, '26-35': 2, '36-45': 3, '46-55': 4, '56+': 5}
data['customer_age_range'] = data['customer_age_range'].map(mapping)


# Drop the original 'customer_age_range' column
data.drop('customer_age_range', axis=1, inplace=True)

In [327]:
data

,gender,sales,units_sold,clients_engaged,click_rate,conversion_rate,year,month,day,campaign_type_Direct Advertising,campaign_type_Email,campaign_type_Online Advertising,campaign_type_Social Networks,campaign_type_TV,region_East,region_North,region_South,region_West
0,1,100735.32,64.0,2364.0,0.13,0.13,2019,2,19,0,0,1,0,0,1,0,0,0
1,0,15722.29,77.0,684.0,0.24,0.13,2019,4,8,0,0,1,0,0,0,1,0,0
2,1,35385.73,1.0,2299.0,0.51,0.08,2018,6,28,0,0,0,0,1,0,1,0,0
3,1,116045.50,44.0,2332.0,0.97,0.09,2019,6,10,0,0,1,0,0,0,0,0,1
4,1,65039.93,20.0,2564.0,0.36,0.26,2018,7,14,0,1,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19974,0,45562.64,8.0,642.0,1.36,0.16,2019,2,5,0,0,1,0,0,1,0,0,0
19975,1,31524.54,65.0,1982.0,0.28,0.03,2018,11,20,0,1,0,0,0,1,0,0,0
19976,0,67450.37,87.0,669.0,0.29,0.19,2021,1,5,0,0,1,0,0,0,0,0,1
19977,1,103822.94,66.0,2670.0,1.22,0.19,2020,9,20,0,0,1,0,0,0,0,0,1
19978,1,70765.63,72.0,2825.0,0.25,0.18,2018,12,17,1,0,0,0,0,0,1,0,0

In [328]:
scaler = MinMaxScaler()
data['sales'] = scaler.fit_transform(data[['sales']])
data['clients_engaged'] = scaler.fit_transform(data[['clients_engaged']])
data.columns

Index(['gender', 'sales', 'units_sold', 'clients_engaged', 'click_rate',
       'conversion_rate', 'year', 'month', 'day',
       'campaign_type_Direct Advertising', 'campaign_type_Email',
       'campaign_type_Online Advertising', 'campaign_type_Social Networks',
       'campaign_type_TV', 'region_East', 'region_North', 'region_South',
       'region_West'],
      dtype='object')

In [329]:
sales_count_by_year = data.groupby('year').size().reset_index(name='sales_count')
# Step 2: Merge the count with the original DataFrame based on 'year'
data = pd.merge(data, sales_count_by_year, on='year', how='left')


import pandas as pd

# Assuming 'data' is your DataFrame containing the relevant columns

# Interaction features
data['units_sold_click_rate'] = data['units_sold'] * data['click_rate']
data['clients_engaged_conversion_rate'] = data['clients_engaged'] * data['conversion_rate']

# Time-related features
data['quarter'] = data['month'].apply(lambda x: (x - 1) // 3 + 1)  # Quarter of the year
data['day_of_week'] = pd.to_datetime(data['year'].astype(str) + '-' + data['month'].astype(str) + '-' + data['day'].astype(str)).dt.dayofweek  # Day of the week


# Transformation features (example: square root transformation)
data['sqrt_sales'] = data['sales'] ** 0.5


# Derived features
data['average_sale_price'] = data['sales'] / data['units_sold']
# Interaction features
data['sales_click_rate_interaction'] = data['sales'] * data['click_rate']

In [330]:
data.columns

Index(['gender', 'sales', 'units_sold', 'clients_engaged', 'click_rate',
       'conversion_rate', 'year', 'month', 'day',
       'campaign_type_Direct Advertising', 'campaign_type_Email',
       'campaign_type_Online Advertising', 'campaign_type_Social Networks',
       'campaign_type_TV', 'region_East', 'region_North', 'region_South',
       'region_West', 'sales_count', 'units_sold_click_rate',
       'clients_engaged_conversion_rate', 'quarter', 'day_of_week',
       'sqrt_sales', 'average_sale_price', 'sales_click_rate_interaction'],
      dtype='object')

In [331]:
train_data = data.iloc[:11998,:]
train_data

,gender,sales,units_sold,clients_engaged,click_rate,conversion_rate,year,month,day,campaign_type_Direct Advertising,...,region_South,region_West,sales_count,units_sold_click_rate,clients_engaged_conversion_rate,quarter,day_of_week,sqrt_sales,average_sale_price,sales_click_rate_interaction
0,1,0.670497,64.0,0.787291,0.13,0.13,2019,2,19,0,...,0,0,3977,8.32,0.102348,1,1,0.818839,0.010477,0.087165
1,0,0.101795,77.0,0.225418,0.24,0.13,2019,4,8,0,...,0,0,3977,18.48,0.029304,2,0,0.319053,0.001322,0.024431
2,1,0.233335,1.0,0.765552,0.51,0.08,2018,6,28,0,...,0,0,3928,0.51,0.061244,2,3,0.483048,0.233335,0.119001
3,1,0.772916,44.0,0.776589,0.97,0.09,2019,6,10,0,...,0,1,3977,42.68,0.069893,2,0,0.879156,0.017566,0.749728
4,1,0.431710,20.0,0.854181,0.36,0.26,2018,7,14,0,...,0,0,3928,7.20,0.222087,3,5,0.657046,0.021585,0.155415
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11993,1,0.528501,80.0,0.733445,1.29,0.27,2018,7,26,0,...,0,0,3928,103.20,0.198030,3,3,0.726981,0.006606,0.681766
11994,2,0.681005,52.0,0.794649,0.41,0.05,2021,9,27,1,...,0,0,3964,21.32,0.039732,3,0,0.825230,0.013096,0.279212
11995,1,0.782026,65.0,0.836455,0.64,0.25,2019,6,1,1,...,1,0,3977,41.60,0.209114,2,5,0.884322,0.012031,0.500497
11996,1,0.028247,59.0,0.911706,0.08,0.08,2020,7,21,0,...,0,0,4044,4.72,0.072936,3,1,0.168070,0.000479,0.002260
11997,0,0.239603,76.0,0.348495,0.53,0.25,2018,8,14,0,...,0,1,3928,40.28,0.087124,3,1,0.489493,0.003153,0.126990

In [332]:
Y = pd.DataFrame(pd.read_csv('train.csv'))['satisfaction_client (%)']
Y.isnull().sum()
Y

0        92.2
1        72.6
2        55.0
3        68.0
4        50.8
         ...
11993    55.4
11994    70.4
11995    70.0
11996    30.0
11997    92.4
Name: satisfaction_client (%), Length: 11998, dtype: float64

In [333]:
data_train = data.iloc[:11998,:].assign(satisfaction_client=Y) 
data_train

,gender,sales,units_sold,clients_engaged,click_rate,conversion_rate,year,month,day,campaign_type_Direct Advertising,...,region_West,sales_count,units_sold_click_rate,clients_engaged_conversion_rate,quarter,day_of_week,sqrt_sales,average_sale_price,sales_click_rate_interaction,satisfaction_client
0,1,0.670497,64.0,0.787291,0.13,0.13,2019,2,19,0,...,0,3977,8.32,0.102348,1,1,0.818839,0.010477,0.087165,92.2
1,0,0.101795,77.0,0.225418,0.24,0.13,2019,4,8,0,...,0,3977,18.48,0.029304,2,0,0.319053,0.001322,0.024431,72.6
2,1,0.233335,1.0,0.765552,0.51,0.08,2018,6,28,0,...,0,3928,0.51,0.061244,2,3,0.483048,0.233335,0.119001,55.0
3,1,0.772916,44.0,0.776589,0.97,0.09,2019,6,10,0,...,1,3977,42.68,0.069893,2,0,0.879156,0.017566,0.749728,68.0
4,1,0.431710,20.0,0.854181,0.36,0.26,2018,7,14,0,...,0,3928,7.20,0.222087,3,5,0.657046,0.021585,0.155415,50.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11993,1,0.528501,80.0,0.733445,1.29,0.27,2018,7,26,0,...,0,3928,103.20,0.198030,3,3,0.726981,0.006606,0.681766,55.4
11994,2,0.681005,52.0,0.794649,0.41,0.05,2021,9,27,1,...,0,3964,21.32,0.039732,3,0,0.825230,0.013096,0.279212,70.4
11995,1,0.782026,65.0,0.836455,0.64,0.25,2019,6,1,1,...,0,3977,41.60,0.209114,2,5,0.884322,0.012031,0.500497,70.0
11996,1,0.028247,59.0,0.911706,0.08,0.08,2020,7,21,0,...,0,4044,4.72,0.072936,3,1,0.168070,0.000479,0.002260,30.0
11997,0,0.239603,76.0,0.348495,0.53,0.25,2018,8,14,0,...,1,3928,40.28,0.087124,3,1,0.489493,0.003153,0.126990,92.4

In [334]:
from sklearn.model_selection import train_test_split
from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error, r2_score

y = data_train["satisfaction_client"]
X = data_train.drop("satisfaction_client", axis=1)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

xgb = XGBRegressor()
xgb.fit(X_train, y_train)
y_pred = xgb.predict(X_test)  # or lgbm.predict(X_test) for LightGBM

from sklearn.feature_selection import SelectFromModel
xgb = XGBRegressor(learning_rate=0.001, max_depth=3, n_estimators=100)
xgb.fit(X, y)
feature_importances = xgb.feature_importances_
selector = SelectFromModel(xgb, threshold='median')
X_selected = selector.fit_transform(X, y)
selected_feature_names = X.columns[selector.get_support()]
X_train_selected, X_test_selected, y_train, y_test = train_test_split(X_selected, y, test_size=0.2, random_state=42)
xgb_selected = XGBRegressor(learning_rate=0.001, max_depth=3, n_estimators=100)
xgb_selected.fit(X_train_selected, y_train)
y_pred_selected = xgb_selected.predict(X_test_selected)
mse_selected = mean_squared_error(y_test, y_pred_selected)
r2_selected = r2_score(y_test, y_pred_selected)
print("Selected Features Model MSE:", mse_selected)
print("Selected Features Model R-squared:", r2_selected)

Selected Features Model MSE: 535.1554831552692
Selected Features Model R-squared: -0.0004112455659919245

In [335]:
from sklearn.model_selection import train_test_split
from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error, r2_score

# Assuming data_train, X, and y are defined earlier
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define XGBoost regressor with tuned parameters
xgb2 = XGBRegressor(learning_rate=0.01,  # Decrease learning rate
                   max_depth=5,          # Adjust max depth
                   n_estimators=500,     # Increase number of estimators
                   reg_alpha=0.1,        # Add L1 regularization
                   reg_lambda=0.1,       # Add L2 regularization
                   subsample=0.8,        # Subsample ratio
                   colsample_bytree=0.8) # Feature subsampling ratio

xgb2.fit(X_train, y_train)
y_pred = xgb.predict(X_test)

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Tuned Model MSE:", mse)
print("Tuned Model R-squared:", r2)

Tuned Model MSE: 534.5986591169608
Tuned Model R-squared: 0.0006296725358667654

In [336]:
data_train

,gender,sales,units_sold,clients_engaged,click_rate,conversion_rate,year,month,day,campaign_type_Direct Advertising,...,region_West,sales_count,units_sold_click_rate,clients_engaged_conversion_rate,quarter,day_of_week,sqrt_sales,average_sale_price,sales_click_rate_interaction,satisfaction_client
0,1,0.670497,64.0,0.787291,0.13,0.13,2019,2,19,0,...,0,3977,8.32,0.102348,1,1,0.818839,0.010477,0.087165,92.2
1,0,0.101795,77.0,0.225418,0.24,0.13,2019,4,8,0,...,0,3977,18.48,0.029304,2,0,0.319053,0.001322,0.024431,72.6
2,1,0.233335,1.0,0.765552,0.51,0.08,2018,6,28,0,...,0,3928,0.51,0.061244,2,3,0.483048,0.233335,0.119001,55.0
3,1,0.772916,44.0,0.776589,0.97,0.09,2019,6,10,0,...,1,3977,42.68,0.069893,2,0,0.879156,0.017566,0.749728,68.0
4,1,0.431710,20.0,0.854181,0.36,0.26,2018,7,14,0,...,0,3928,7.20,0.222087,3,5,0.657046,0.021585,0.155415,50.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11993,1,0.528501,80.0,0.733445,1.29,0.27,2018,7,26,0,...,0,3928,103.20,0.198030,3,3,0.726981,0.006606,0.681766,55.4
11994,2,0.681005,52.0,0.794649,0.41,0.05,2021,9,27,1,...,0,3964,21.32,0.039732,3,0,0.825230,0.013096,0.279212,70.4
11995,1,0.782026,65.0,0.836455,0.64,0.25,2019,6,1,1,...,0,3977,41.60,0.209114,2,5,0.884322,0.012031,0.500497,70.0
11996,1,0.028247,59.0,0.911706,0.08,0.08,2020,7,21,0,...,0,4044,4.72,0.072936,3,1,0.168070,0.000479,0.002260,30.0
11997,0,0.239603,76.0,0.348495,0.53,0.25,2018,8,14,0,...,1,3928,40.28,0.087124,3,1,0.489493,0.003153,0.126990,92.4

In [337]:
test_data = data.iloc[11998:,:]


X_test = test_data 
y_pred_test = xgb.predict(X_test)
y_pred_test

array([60.04848 , 60.13976 , 60.192974, ..., 60.04848 , 60.192974,
       60.25442 ], dtype=float32)

In [338]:
df_test = pd.DataFrame(pd.read_csv('test.csv'))
ID = df_test['ID']
predictions_df = pd.DataFrame({'ID': ID, 'satisfaction_client': y_pred_test})
csv_file_path = 'predicted_satisfaction_client.csv'
predictions_df.to_csv(csv_file_path, index=False)